name: Deploy to EC2 with SSH key passphrase

on:
  push:
    branches:
      - staging  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key with passphrase
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.EC2_SSH_KEY }}" | ssh-keygen -p -P "${{ secrets.EC2_SSH_PASSPHRASE }}" -N "" -f /dev/stdin)
        shell: bash

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/your-app-folder
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
