name: Deploy to EC2 with SSH passphrase

on:
  push:
    branches:
      - staging  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key with passphrase
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          # Use ssh-askpass trick
          sudo apt-get update
          sudo apt-get install -y ssh-askpass

          DISPLAY=:0
          SSH_ASKPASS=$(which ssh-askpass)
          export DISPLAY SSH_ASKPASS

          setsid ssh-add key.pem <<< "${{ secrets.EC2_SSH_PASSPHRASE }}"

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/your-app-folder
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
