name: Deploy to EC2 with SSH passphrase

on:
  push:
    branches:
      - staging  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key with passphrase
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Start ssh-agent
          eval "$(ssh-agent -s)"

          # Workaround for passphrase using ssh-askpass
          sudo apt-get update
          sudo apt-get install -y ssh-askpass

          export DISPLAY=:0
          export SSH_ASKPASS=$(command -v ssh-askpass)
          echo "${{ secrets.EC2_SSH_PASSPHRASE }}" > passphrase.txt
          chmod +x passphrase.txt

          # Use setsid to allow SSH_ASKPASS to provide passphrase
          setsid ssh-add ~/.ssh/id_rsa < passphrase.txt

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/your-app-folder
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
